# Generated by Django 5.2.17 on 2026-08-07 04:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin')], default='admin', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.BigIntegerField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('needs_review', 'Needs Review')], default='complete', max_length=20)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('manual', 'Manual')], max_length=10)),
                ('title', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='wellness.period')),
            ],
            options={
                'ordering': ('-period_start',),
            },
        ),
        migrations.CreateModel(
            name='ImportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_warned', models.IntegerField(default=0)),
                ('rows_rejected', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='wellness.period')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.IntegerField(default=0)),
                ('calls_recd', models.IntegerField(default=0)),
                ('calls_out', models.IntegerField(default=0)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_modes', to='wellness.period')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('new', 'New'), ('followup', 'Follow-up')], max_length=10)),
                ('vertical', models.CharField(choices=[('WC', 'Wellness Centre'), ('YD', 'Your Dost'), ('MW', 'Myndwell')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cases', models.IntegerField(default=0)),
                ('gender_male', models.IntegerField(default=0)),
                ('gender_female', models.IntegerField(default=0)),
                ('gender_other', models.IntegerField(default=0)),
                ('mode_online', models.IntegerField(default=0)),
                ('mode_in_person', models.IntegerField(default=0)),
                ('mode_phone', models.IntegerField(default=0)),
                ('referral_self', models.IntegerField(default=0)),
                ('referral_director', models.IntegerField(default=0)),
                ('referral_dean', models.IntegerField(default=0)),
                ('referral_friend', models.IntegerField(default=0)),
                ('referral_mitr', models.IntegerField(default=0)),
                ('concern_anxiety', models.IntegerField(default=0)),
                ('concern_stress', models.IntegerField(default=0)),
                ('concern_career', models.IntegerField(default=0)),
                ('concern_interpersonal', models.IntegerField(default=0)),
                ('concern_self_dev', models.IntegerField(default=0)),
                ('concern_clinical', models.IntegerField(default=0)),
                ('concern_addiction', models.IntegerField(default=0)),
                ('concern_medical', models.IntegerField(default=0)),
                ('concern_suicidal', models.IntegerField(default=0)),
                ('stake_ug', models.IntegerField(default=0)),
                ('stake_pg', models.IntegerField(default=0)),
                ('stake_phd', models.IntegerField(default=0)),
                ('stake_dual', models.IntegerField(default=0)),
                ('stake_faculty', models.IntegerField(default=0)),
                ('stake_employee_family', models.IntegerField(default=0)),
                ('stake_postdoc', models.IntegerField(default=0)),
                ('stake_unidentified', models.IntegerField(default=0)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_rows', to='wellness.period')),
            ],
            options={
                'ordering': ('case_type', 'vertical'),
            },
        ),
        migrations.CreateModel(
            name='RawSubteamRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=10)),
                ('sub_team', models.CharField(max_length=20)),
                ('entry_no', models.CharField(blank=True, default='', max_length=10)),
                ('source', models.CharField(max_length=10)),
                ('raw_payload', models.JSONField(default=dict)),
                ('check_results', models.JSONField(default=dict)),
                ('needs_review', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='wellness.period')),
            ],
            options={
                'ordering': ('case_type', 'sub_team'),
            },
        ),
        migrations.CreateModel(
            name='SecondaryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(choices=[('WC', 'Wc'), ('YD', 'Yd'), ('MW', 'Mw'), ('Total', 'Total')], max_length=10)),
                ('total_sessions', models.IntegerField(default=0)),
                ('early_prevention_warning', models.IntegerField(default=0)),
                ('no_show_turn_up', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('clients_over_4_sessions', models.IntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_metrics', to='wellness.period')),
            ],
            options={
                'ordering': ('vertical',),
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_by__isnull', True)), fields=('report_type', 'period_start', 'period_end'), name='uniq_active_period'),
        ),
        migrations.AddConstraint(
            model_name='caserow',
            constraint=models.UniqueConstraint(fields=('period', 'case_type', 'vertical'), name='uniq_case_row'),
        ),
        migrations.AddConstraint(
            model_name='secondarymetrics',
            constraint=models.UniqueConstraint(fields=('period', 'vertical'), name='uniq_secondary_metric'),
        ),
    ]
