# Generated by Django 5.2.17 on 2026-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserow',
            name='vertical',
            field=models.CharField(choices=[('WC', 'Wellness Centre'), ('TA', 'Team A'), ('YD', 'Your Dost'), ('MW', 'Myndwell')], max_length=5),
        ),
        migrations.AlterField(
            model_name='secondarymetrics',
            name='vertical',
            field=models.CharField(choices=[('WC', 'Wc'), ('TA', 'Ta'), ('YD', 'Yd'), ('MW', 'Mw'), ('Total', 'Total')], max_length=10),
        ),
    ]
