# Generated by Django 5.2.17 on 2026-09-04 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_alter_caserow_vertical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('responsible_person', models.CharField(blank=True, default='', max_length=255)),
                ('responsible_team', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='not_started', max_length=20)),
                ('actual_result', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, default='', max_length=20)),
                ('source_period_id', models.IntegerField(blank=True, null=True)),
                ('source_mode', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
